Repository AY2122S2-CS2103T-T11-3/tp, pull requests merged in 2022-04, with the labels that each got.

#189 Fix normal tag same name as priority or status tag
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Bug, priority.Medium, severity.Medium

#190 Update User Guide with new warnings and other updates
  docs/UserGuide.md
Labels: priority.Medium, severity.Low

#216 Doc - Updated laugingkid-sg.md for PPP requirements.
  docs/team/laughingkid-sg.md
Labels: type.Task, priority.High
