Repository AY2122S2-CS2103T-T11-3/tp, pull requests merged in 2022-03, with the labels that each got.

#40 Branch refactor model classes
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/InternApplyMemory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyInternApplyMemory.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#45 Refactoring the classes in Logic folder to align with InternApply
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/InternApplyParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/InternApplyParserTest.java
Labels: type.Task, priority.Medium

#50 Add job title field
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/application/Application.java
  src/main/java/seedu/address/model/application/JobTitle.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedApplication.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#66 48 65 refactor UI classes and mainapp
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/ApplicationCard.java
  src/main/java/seedu/address/ui/ApplicationListPanel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/ApplicationListPanel.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.Medium

#71 Refactor Commons Classes and additional changes
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Task, priority.Medium

#64 Modify JsonAdaptedTag toModelType method
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
Labels: type.Bug, priority.High, severity.High

#74 Update relevant messages for all commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditApplicationDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/InternApplyParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.Medium, severity.VeryLow

#78 Fix minor bug with add command message usage
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug, priority.Medium

#79 Create exceptions for wrong input format when adding tags
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/ApplicationStatusTagType.java
  src/main/java/seedu/address/model/tag/PriorityTagType.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/TagType.java
Labels: type.Task, priority.High

#84 Update to JUnit tests imported from AB3 code base
  src/main/java/seedu/address/storage/JsonSerializableInternApply.java
  src/test/data/JsonInternApplyStorageTest/invalidAndValidApplicationInternApplyMemory.json
  src/test/data/JsonInternApplyStorageTest/invalidApplicationInternApplyMemory.json
  src/test/data/JsonInternApplyStorageTest/notJsonFormatInternApplyMemory.json
  src/test/data/JsonSerializableInternApplyMemoryTest/duplicateApplicationInternApplyMemory.json
  src/test/data/JsonSerializableInternApplyMemoryTest/invalidApplicationInternApplyMemory.json
  src/test/data/JsonSerializableInternApplyMemoryTest/typicalApplicationInternApplyMemory.json
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditApplicationDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/InternApplyParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/InternApplyMemoryTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/application/ApplicationTest.java
  src/test/java/seedu/address/model/application/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/application/NameTest.java
  src/test/java/seedu/address/model/application/UniqueApplicationListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/address/storage/JsonInternApplyStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableInternApplyTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/ApplicationBuilder.java
  src/test/java/seedu/address/testutil/ApplicationUtil.java
  src/test/java/seedu/address/testutil/EditApplicationDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InternApplyMemoryBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalApplications.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#87 Fix Checkstyle Errors
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditApplicationDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/InternApplyParserTest.java
  src/test/java/seedu/address/model/InternApplyMemoryTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/application/ApplicationTest.java
  src/test/java/seedu/address/model/application/UniqueApplicationListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/address/storage/JsonInternApplyStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableInternApplyTest.java
  src/test/java/seedu/address/testutil/TypicalApplications.java
Labels: type.Bug, priority.High

#86 Update user guide edit command
  docs/UserGuide.md
Labels: type.Task, priority.High

#88 Update test data for testcases
  src/test/data/JsonSerializableInternApplyMemoryTest/duplicateApplicationInternApplyMemory.json
  src/test/data/JsonSerializableInternApplyMemoryTest/typicalApplicationInternApplyMemory.json
  src/test/java/seedu/address/storage/JsonInternApplyStorageTest.java
  src/test/java/seedu/address/testutil/TypicalApplications.java
Labels: type.Task, priority.Medium

#89 Update UG for Interview Slot
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#90 Add test cases for InterviewSlot
  src/main/java/seedu/address/model/application/InterviewSlot.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/application/ApplicationTest.java
  src/test/java/seedu/address/model/application/InterviewSlotTest.java
  src/test/java/seedu/address/testutil/EditApplicationDescriptorBuilder.java
Labels: type.Task, priority.High

#91 Fix Tag constructor to create correct application status tag
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Bug, severity.Medium

#92 Changes made to UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, severity.VeryLow

#93 Addition of Testcases for Tag class
  src/test/java/seedu/address/model/tag/ApplicationStatusTagTest.java
  src/test/java/seedu/address/model/tag/JobScopeTagTest.java
  src/test/java/seedu/address/model/tag/PriorityTagTest.java
Labels: priority.Medium, severity.VeryLow

#98 Update index.md
  docs/index.md
Labels: type.Task, priority.Medium

#95 Tag Constructor modification
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Task, priority.Medium, severity.VeryLow

#111 Feature - Add Details to application
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui-after-details-update.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/application/Application.java
  src/main/java/seedu/address/model/application/Details.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedApplication.java
  src/main/java/seedu/address/ui/ApplicationCard.java
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableInternApplyMemoryTest/duplicateApplicationInternApplyMemory.json
  src/test/data/JsonSerializableInternApplyMemoryTest/typicalApplicationInternApplyMemory.json
  src/test/java/seedu/address/storage/JsonAdaptedApplicationTest.java
  src/test/java/seedu/address/testutil/ApplicationBuilder.java
  src/test/java/seedu/address/testutil/TypicalApplications.java
Labels: type.Epic, severity.High

#126 FIX - Result Display and details field
  src/main/resources/view/ApplicationListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Bug, severity.Low

#131 Docs - Update UG caa 280322 0956H
  docs/UserGuide.md
  docs/images/MainWindowUi.png
  docs/images/ReminderWindowUi.png
  docs/images/Ui.png
Labels: type.Task, priority.High

#134 Fix-Tag-Details-Ui
  src/main/java/seedu/address/commons/util/Colors.java
  src/main/java/seedu/address/ui/TagBox.java
  src/main/resources/view/ApplicationListCard.fxml
Labels: type.Bug, severity.VeryLow
